name: Pre-deploy
on: 
  push:
    branches:
      - '!main'
jobs:
  pre_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Fetch all commits, instead of shallow fetch
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install project dependencies
        run: pnpm install --frozen-lockfile
      - name: Run ESLint
        run: pnpm run ci:lint
      - name: Run unit tests
        run: pnpm run ci:unit-tests
      - name: Run end-to-end tests
        run: pnpm run ci:e2e-tests
